### ISSUE TITLE
Deobfuscator integration

### ISSUE THREAD

**Issue by ecx86** [LLVM-but-worse/jda#8]

**Comment by Chnkr** [comment]
You might want to look into https://github.com/java-deobfuscator/deobfuscator which seems to be an interesting project.

**Comment by ecx86** [comment]
@Chnkr thats what i was thinking of

**Comment by Chnkr** [comment]
:+1:

**Comment by ecx86** [comment]
Now that the plugin API is taking hold, this should be implemented as a plugin instead.
